# Describes the format for available HomeKit services

reload:
reset_accessory:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          multiple: true

unpair:
  fields:
    device_id:
      required: true
      selector:
        device:
          multiple: true
          integration: homekit
