generate_text:
  fields:
    task_name:
      example: "home summary"
      required: true
      selector:
        text:
    instructions:
      example: "Funny notification that garage door left open"
      required: true
      selector:
        text:
    entity_id:
      required: false
      selector:
        entity:
          domain: llm_task
